[workspace]
package.version = "0.4.2"
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
cudarc = "0.9.14" 
ndarray = "0.16.1"
ndarray-rand = "0.15.0"
safetensors = "0.4.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.49"